export const subtitles: string[] = [
    '"Alternative title: Color My Vibe (rejected for childishness)"',
    '"Alternative title: Noise My Vibe (rejected to lower ESRB rating)"',
    '"Touch thumb to touchscreen to continue..."',
    '"Breathe in... Breathe out..."',
    '"Breathe in... Hold... Keep holding..."',
    '"Feel free to right-click"',
    '"Taste the fun colors"',
    '"0/10 Needs more quips"',
    '"3/10 Not enough colors"',
    '"Ohhhhmmmmmmm......"',
    '"Fun for all ages"',
    '"Mood My Noise"',
    '"Rated E for Everyone"',
    '"Who needs drugs?"',
    '"Free Palestine!"',
    '"Free Ukraine!"',
    '"Durgz Mod for Garry\'s Mod 12"',
    '"Also try gently pressing your closed eyes"',
    '"Error Code 420 (real)"',
    '"We do not endorse illegal use of drugs"',
    '"Also try Watch Dogs\' Digital Trips!"',
    '"Created by Hatsune Miku!"'
]